"""add activities tables

Revision ID: 16bd11bc7508
Revises: 5181d69a800e
Create Date: 2026-01-28 21:47:21.013132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bd11bc7508'
down_revision = '5181d69a800e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('commit', 'issue', 'pull_request', name='activity_type'), nullable=False),
    sa.Column('github_event_id', sa.BigInteger(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_event_id', name='uq_activity_repo_ghevent')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_repository_id'), ['repository_id'], unique=False)

    op.create_table('commit_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('additions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deletions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commit_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commit_activities_activity_id'), ['activity_id'], unique=True)

    op.create_table('issue_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_activities_activity_id'), ['activity_id'], unique=True)

    op.create_table('pull_request_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('merged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_request_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_request_activities_activity_id'), ['activity_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_request_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_request_activities_activity_id'))

    op.drop_table('pull_request_activities')
    with op.batch_alter_table('issue_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_activities_activity_id'))

    op.drop_table('issue_activities')
    with op.batch_alter_table('commit_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commit_activities_activity_id'))

    op.drop_table('commit_activities')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_repository_id'))
        batch_op.drop_index(batch_op.f('ix_activities_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_activities_actor'))

    op.drop_table('activities')
    # ### end Alembic commands ###
