"""store encrypted github token

Revision ID: 5181d69a800e
Revises: f5ebba912374
Create Date: 2026-01-28 20:51:10.403896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5181d69a800e'
down_revision = 'f5ebba912374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_encrypted', sa.Text(), nullable=False))
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('token_encrypted')

    # ### end Alembic commands ###
