"""change github_event_id to string

Revision ID: e6fe242a55a4
Revises: 16bd11bc7508
Create Date: 2026-01-28 22:03:05.045124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fe242a55a4'
down_revision = '16bd11bc7508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('github_event_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('github_event_id',
               existing_type=sa.String(length=64),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
